### PR TITLE
Fix #289; fix textures for scivis renderer

### LINKED ISSUE #289: Reduce frequency of progress updates
If a lot of morphologies are loaded, it generates a huge load of messages. Maybe in general all message sends should be throttled. Reuse the image stream fps?

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

File: plugins/engines/ospray/OSPRayScene.cpp [hunk 1]
```diff
@@ -43,11 +43,12 @@ struct TextureTypeMaterialAttribute
...
 };
 
-static TextureTypeMaterialAttribute textureTypeMaterialAttribute[7] = {
+static TextureTypeMaterialAttribute textureTypeMaterialAttribute[8] = {
     {TT_DIFFUSE, "map_kd"},
     {TT_NORMALS, "map_bump"},
+    {TT_BUMP, "map_bump"},
     {TT_SPECULAR, "map_ks"},
-    {TT_EMISSIVE, "map_a"},
+    {TT_EMISSIVE, "map_Ns"},
```
Comment (favreau) [inline plugins/engines/ospray/OSPRayScene.cpp]: Any reason why this one has capital N, when all other attributes are lowercase? convention? gltf?

Comment (tribal-tec) [reply plugins/engines/ospray/OSPRayScene.cpp]: no, ospray. but they also accept lower-case 'n'. I'll change it
